### ISSUE TITLE
Issue with selling to npc at end.

### ISSUE THREAD

**Issue by arpkaz** [arabcodingteam/qb-hunting#1]
You can not sell to the NPC at the "Legal Sell" point, it does not do anything when using the third eye and clicking sell! - Got everything else working. Great so far!

**Comment by krrm1** [comment]
i will check it

**Comment by arpkaz** [comment]
Appreciate it boss

**Comment by krrm1** [comment]
https://github.com/arabcodingteam/arabcodingteam-hunting

**Comment by krrm1** [comment]
im lazy to do code fix it you can redownload it now
